number=int(input("enter number:"))
print(type(number))
print(number)
number=float(input("enter number:"))
print(type(number))
print(number)
number=float(input("enter number:"))
print(type(number))
print(number)