name=input("enter your name:")
print(name)
print(type(name))
surname=input("enter your surname:")
age=input("enter your age:")
print(age)
print(type(age))
num=input("enter number:")
print(type(num))
num1=("enter your number1:")
print(type(num1))